### ISSUE TITLE
Clone/Copy multiple branches/dirs/files

### ISSUE THREAD

**Issue by Angelk90** [vorillaz/ploff#4]
Hi! @vorillaz, congratulations for the project, it would be possible to do something similar to this:

1) `ploff https://github.com/git/git.git -b develop, next`
2) `ploff https://github.com/git/git.git -o builtin, compat, contrib`
3) `ploff https://github.com/git/git.git -o Makefile, README.md`

**Comment by vorillaz** [comment]
Hey @Angelk90, thanks a lot for your kind words. It should possible but a bit tricky especially for branches without targets since they can override the same folders / files over and over again.

**Comment by vorillaz** [comment]
Hey @Angelk90, under the hood `ploff` uses [`git sparse-chechout`](https://git-scm.com/docs/git-sparse-checkout).

You can achieve the same thing with `git` regarding multiple files / folders as:
```bash
mkdir tmp-git # create folder
cd tmp-git # go to folder
git clone -n --depth=1 --filter=tree:0 https://github.com/git/git.git . # shallow clone master branch or use `-b my-branch`
git sparse-checkout set --no-cone builtin compat contrib # sparse checkout folders
git checkout # and you're done
```

This will partially check out the `builtin`, `compat` and `contribut` folders, when it comes to branches though things are getting complicated. Any folder can exist in multiple branches with different file/folder structure, thus cloning from different branches can override the destination, introducing a mess.

If you need this feature you can simply create something on top of `ploff/lib.js` which is actually exposed through the NPM package.

**Comment by vorillaz** [comment]
Closing this one due to inactivity.
